### ISSUE TITLE
python3 error and --askpass option

### ISSUE THREAD

**Issue by hcraT** [krig/parallel-ssh#1]
Hi,
when I use the program while enabling the --askpass option I get this error:

<pre>
Traceback (most recent call last):
  File "/usr/bin/pssh", line 118, in <module>
    do_pssh(hosts, cmdline, opts)
  File "/usr/bin/pssh", line 89, in do_pssh
    statuses = manager.run()
  File "/usr/lib/python3.4/site-packages/psshlib/manager.py", line 74, in run
    self.iomap.poll(wait)
  File "/usr/lib/python3.4/site-packages/psshlib/manager.py", line 255, in poll
    handler(fd, self)
  File "/usr/lib/python3.4/site-packages/psshlib/askpass_server.py", line 72, in handle_write
    bytes_written = conn.send(buffer)
TypeError: 'str' does not support the buffer interface
</pre>

this can be corrected by changing this line:

``` python
        self.buffermap[fd] = self.password
```

to:

``` python
        self.buffermap[fd] = self.password.encode()
```

Best regards.

**Comment by krig** [comment]
Thanks!
